# 볼린저 밴드 스퀴즈 돌파 전략 설정
# 좁아지다가 좁은 상태를 유지하는 조건을 활용한 고급 설정

count = 2                # 확인 캔들 수
period = 20              # 볼린저 밴드 계산 기간
multiplier = 2.0         # 볼린저 밴드 승수 (표준편차 배수)

# 스퀴즈 패턴 설정
narrowing_period = 7     # 밴드 폭 감소 확인 기간 (더 긴 기간으로 설정)
squeeze_period = 8       # 좁은 상태 유지 기간 (스퀴즈 유지 기간)
squeeze_threshold = 0.015 # 스퀴즈 임계값 (더 엄격한 조건, 1.5%) 