# RSI 전략 설정
rsi_period = 14         # RSI 계산 기간
rsi_upper = 70.0        # RSI 상단 기준값 (이 값보다 높으면 과매수)
rsi_lower = 30.0        # RSI 하단 기준값 (이 값보다 낮으면 과매도)
rsi_count = 3           # RSI 판정 횟수 (연속으로 조건이 만족되어야 하는 횟수)
ma_periods = [20, 50]   # 이동평균 기간 배열 (짧은 기간에서 긴 기간 순으로 정렬) 