# 멀티 타임프레임 전략 설정

# 타임프레임 목록 (콤마로 구분)
# 지원 타임프레임: 1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
timeframes = "1m,5m,15m,1h"

# 각 타임프레임의 신호 가중치 (콤마로 구분)
# 가중치 합은 1.0이어야 함
weights = "0.1,0.2,0.3,0.4"

# 기본 전략 유형
# 지원 전략: ma, ma_short, rsi, rsi_short, macd, macd_short, bband, bband_short, three_rsi, three_rsi_short
base_strategy = "rsi"

# 신호 확인 임계값 (0.0 ~ 1.0)
# 가중 평균 신호가 이 값보다 크면 매수, 작으면 매도
confirmation_threshold = 0.6

# 각 기본 전략별 설정
# RSI 전략 설정
period = 14
oversold = 30 
overbought = 70 